SELECT 
  route, 
  CONCAT(ROUND(sum(D_BETWEEN_DIST), 1), 'km') AS TOTAL_DISTANCE,
  CONCAT(ROUND(AVG(D_BETWEEN_DIST), 2), 'km') AS AVERAGE_DISTANCE
FROM subway_distance
GROUP BY route
ORDER BY MAX(D_CUMULATIVE) - MIN(D_CUMULATIVE) DESC;